export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
// app/submissions/meeting-request/layout.tsx


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
